---
title: "O2 Time Series Demo - Dygraphs"
author: "Alison Appling"
date: "June 19, 2017"
output: 
  ioslides_presentation: 
    theme: flatly
    highlight: bclear
    css: o2demo.css
    smaller: yes
    widescreen: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(dataRetrieval)
library(geoknife)
library(dygraphs)
library(xts)
library(dplyr)
library(ggplot2)
library(streamMetabolizer)
library(mda.streams)
library(unitted)
library(cowplot)
```

```{r getnwis, cache=TRUE, include=FALSE}
# library(dataRetrieval)
# o2data_raw <- readNWISuv(
#   siteNumbers='02336300', parameterCd='00300', 
#   startDate='2013-01-01', endDate='2017-06-18', tz='UTC')
# o2data <- renameNWISColumns(o2data_raw)
# saveRDS(o2data, 'o2data.Rds')
o2data <- readRDS('o2data.Rds')
```

```{r dygraph, include=FALSE}
library(dygraphs)
library(xts)
o2data_xts <- xts(o2data$DO_Inst, o2data$dateTime)
d <- dygraph(o2data_xts) %>% dygraphs::dyOptions(colors='cornflowerblue')
```

## Explore: dygraphs for interaction

```{r print_dygraph, fig.width=9.5, fig.height=5}
d
```
